---
title: "ANOVA 2 locations"
author: "Marius Buydens"
date: "24-6-2019"
output: html_document
---

# Difference between sites B4N01 and B4S03 in terms of total density

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install/load packages
```{r}
library("readxl")
library("car")
library("ggpubr")
library("ggplot2")
```

# Loading and inspecting the dataset

```{r}
# read dataset:

TD <- read_excel(path = "/Users/lailabuydens/Desktop/excel_scripts_thesis/Nodule_crevice.xlsx", sheet = "2_LOC", col_names = TRUE, col_types = NULL, na = "", skip = 0)
head(TD) # check dataset
```

```{r}
# Visualizing the data

ggboxplot(TD, x = "location_ID", y = "square_root_transform_true", color = "location", palette = c("#FF8000", "#B40431"),
          order = c("B6S02", "B4NO1"),
          ylab = expression(bold("Total density")), xlab = expression(bold("Location")))

```


# Before ANOVA: check for assumptions (= data is normally distributed + variances are equal between locations)

```{r}

## testing for normality: visual test with QQ-plots and Shapiro-Wilk normality test PER LOCATION (H0: normal distribution => p<0.05: reject hypothesis => no normal distribution)

# per location check for normal distribution of raw data
B6S02 <- TD$TD_relative[1:15]
B4N01 <- TD$TD_relative[16:30]


# visual check
par(mfrow = c(1, 2))
qqPlot(B6S02)
qqPlot(B4N01)


# check data
shapiro.test(B6S02)
shapiro.test(B4N01)

#results: normal distribution

```


# testing for homogeneity of variances
```{r}

leveneTest(TD$TD_relative, TD$location, center = mean) 

# result: H0 (= no significant difference in variances between the locations) is not rejected => variances are homogeneous => assumption is met 
```


# 1-way ANOVA
```{r}
anova = aov(TD_relative~location, data=TD)
summary(anova)

# result: Significant difference (p < 0.05) between location B6S02 and B4N01
```


# Tukey test
```{r}
test <- TukeyHSD(anova)
plot(test)
```